=== srug86/restaurant-management-using-nfc.doc/listings/bill.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Bill (Company, Client, Info, Orders, PriceSummary, Paid)>
<!ELEMENT Company (NIF, Address, Contact)>
<!ATTLIST Company name (#PCDATA)>
<!ELEMENT NIF (#PCDATA)>
<!ELEMENT Contact (Phone, Fax, Email)>
<!ELEMENT Phone (#PCDATA)>
<!ELEMENT Fax (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Client (DNI, Name, Surname, Address)>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Surname (#PCDATA)>
<!ELEMENT Address (Street, Number, ZipCode, Town, State)>
<!ELEMENT Street (#PCDATA)>
<!ELEMENT ZipCode (#PCDATA)>
<!ELEMENT Town (#PCDATA)>
<!ELEMENT State (#PCDATA>
<!ELEMENT Info (Number, Serial, Date, Table)>
<!ELEMENT Number (#PCDATA)>
<!ELEMENT Serial (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Table (#PCDATA)>
<!ELEMENT Orders (Order)+>
<!ELEMENT Order (Product, Amount, Price, Discount, Total)>
<!ATTLIST Order id (#PCDATA)>
<!ELEMENT Product (#PCDATA)>
<!ELEMENT Amount (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT PriceSummary (Subtotal, Discount, TaxBase, IVA, Quote, Total)>
<!ELEMENT Subtotal (#PCDATA)>
<!ELEMENT Discount (#PCDATA)>
<!ELEMENT TaxBase (#PCDATA)>
<!ELEMENT IVA (#PCDATA)>
<!ELEMENT Quote (#PCDATA)>
<!ELEMENT Total (#PCDATA)>
<!ELEMENT Paid (#PCDATA)>

=== srug86/restaurant-management-using-nfc.doc/listings/bill.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bill SYSTEM "bill.dtd">
<Bill>
	<Company name="MobiCarta">
		<NIF>70389210A</NIF>
		<Address>
			<Street>Paseo de la Universidad</Street>
			<Number>14</Number>
			<ZipCode>13071</ZipCode>
			<Town>Ciudad Real</Town>
			<State>Ciudad Real</State>
		</Address>
		<Contact>
			<Phone>926291111</Phone>
			<Fax>926294444</Fax>
			<Email>clients@mobicarta.es</Email>
		</Contact>
	</Company>
	<Client>
		<DNI>05692939W</DNI>
		<Name>Sergio</Name>
		<Surname>de la Rubia</Surname>
		<Address>
			<Street>C/Pedro Oviedo</Street>
			<Number>36</Number>
			<ZipCode>13270</ZipCode>
			<Town>Almagro</Town>
			<State>Ciudad Real</State>
		</Address>
	</Client>
	<Info>
		<Number>1</Number>
		<Serial>1</Serial>
		<Date>2012:04:04 22:18:55</Date>
		<Table>2</Table>
	</Info>
	<Orders>
		<Order id="4">
			<Product>Coca Cola 200ml</Product>
			<Amount>2</Amount>
			<Price>1.5<Price>
			<Discount>0</Discount>
			<Total>3</Total>
		</Order>
		<Order id="12">
			<Product>Solomillo a la pimienta</Product>
			<Amount>2</Amount>
			<Price>5<Price>
			<Discount>0</Discount>
			<Total>10</Total>
		</Order>
	</Orders>
	<PriceSummary>
		<Subtotal>13</Subtotal>
		<Discount>0</Discount>
		<TaxBase>13</TaxBase>
		<IVA>18</IVA>
		<Quote>2.34</Quote>
		<Total>15.34</Total>
	</PriceSummary>
	<Paid>0</Paid>
</Bill>
