=== srug86/restaurant-management-using-nfc.doc/listings/orders.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Orders (Order)+>
<!ELEMENT Order (Table, Product, Amount, Status, Date)>
<!ATTLIST Order id (#PCDATA)>
<!ELEMENT Table (#PCDATA)>
<!ELEMENT Product (#PCDATA)>
<!ELEMENT Amount (#PCDATA)>
<!ELEMENT Status (#PCDATA)>
<!ELEMENT Date (#PCDATA)>

=== srug86/restaurant-management-using-nfc.doc/listings/orders.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE orders SYSTEM "orders.dtd">
<Orders>
	<Order id="8">
		<Table>7</Table>
		<Product>Macarrones con tomate</Product>
		<Amount>2</Amount>
		<Status>0</Status>
		<Date>2012-04-25 14:30:23</Date>
	</Order>
	<Order id="9">
		<Table>7</Table>
		<Product>Sepia a la plancha</Product>
		<Amount>1</Amount>
		<Status>0</Status>
		<Date>2012-04-25 14:32:50</Date>
	</Order>
</Orders>
