=== srug86/restaurant-management-using-nfc.doc/listings/products.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Products (Product)+>
<!ELEMENT Product (Category, Price, Description, Visible, Discount, DiscountedUnit)>
<!ATTLIST Product name (#PCDATA)>
<!ELEMENT Category (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Visible (#PCDATA)>
<!ELEMENT Discount (#PCDATA)>
<!ELEMENT DiscountedUnit (#PCDATA)>

=== srug86/restaurant-management-using-nfc.doc/listings/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE products SYSTEM "products.dtd">
<Products>
	<Product name="Ensalada mixta">
		<Category>Entrantes</Category>
		<Price>5</Price>
		<Description>ensalada,vegetal,tomate,lechuga</Description>
		<Visible>True</Visible>
		<Discount>0</Discount>
		<DiscountedUnit>0</DiscountedUnit>
	</Product>
	<Product name="Sopa de marisco">
		<Category>Entrantes</Category>
		<Price>6</Price>
		<Description>sopa,marisco</Description>
		<Visible>True</Visible>
		<Discount>0</Discount>
		<DiscountedUnit>0</DiscountedUnit>
	</Product>
	<Product name="Pulpo a la gallega">
		<Category>Entrantes</Category>
		<Price>12</Price>
		<Description>pulpo,molusco</Description>
		<Visible>False</Visible>
		<Discount>0</Discount>
		<DiscountedUnit>0</DiscountedUnit>
	</Product>
	<Product name="Paella de marisco">
		<Category>Arroces y pastas</Category>
		<Price>12,5</Price>
		<Description>arroz,marisco</Description>
		<Visible>True</Visible>
		<Discount>0</Discount>
		<DiscountedUnit>0</DiscountedUnit>
	</Product>
	<Product name="Spaghetti a la bolognesa">
		<Category>Arroces y pastas</Category>
		<Price>10,5</Price>
		<Description>pasta,spaghetti</Description>
		<Visible>True</Visible>
		<Discount>0</Discount>
		<DiscountedUnit>0</DiscountedUnit>
	</Product>
	<Product name="Macarrones con tomate">
		<Category>Arroces y pastas</Category>
		<Price>10</Price>
		<Description>pasta,macarron,tomate</Description>
		<Visible>True</Visible>
		<Discount>0,5</Discount>
		<DiscountedUnit>2</DiscountedUnit>
	</Product>
	<Product name="Cochinillo casero">
		<Category>Carnes</Category>
		<Price>20,5</Price>
		<Description>cerdo,horno</Description>
		<Visible>True</Visible>
		<Discount>0</Discount>
		<DiscountedUnit>0</DiscountedUnit>
	</Product>
	<Product name="Costillas de cordero">
		<Category>Carnes</Category>
		<Price>12,5</Price>
		<Description>costilla,cordero</Description>
		<Visible>True</Visible>
		<Discount>0</Discount>
		<DiscountedUnit>0</DiscountedUnit>
	</Product>
	<Product name="Solomillo de ternera">
		<Category>Carnes</Category>
		<Price>23</Price>
		<Description>solomillo,ternera</Description>
		<Visible>True</Visible>
		<Discount>0</Discount>
		<DiscountedUnit>0</DiscountedUnit>
	</Product>
	<Product name="Pollo al horno">
		<Category>Carnes</Category>
		<Price>8,55</Price>
		<Description>pollo,horno</Description>
		<Visible>True</Visible>
		<Discount>0</Discount>
		<DiscountedUnit>0</DiscountedUnit>
	</Product>
	<Product name="Sepia a la plancha">
		<Category>Pescados y mariscos</Category>
		<Price>13,5</Price>
		<Description>molusco,plancha</Description>
		<Visible>True</Visible>
		<Discount>0</Discount>
		<DiscountedUnit>0</DiscountedUnit>
	</Product>
	<Product name="Lenguado a la plancha">
		<Category>Pescados y mariscos</Category>
		<Price>20,35</Price>
		<Description>pescado,lenguado,plancha</Description>
		<Visible>True</Visible>
		<Discount>0</Discount>
		<DiscountedUnit>0</DiscountedUnit>
	</Product>
	<Product name="Lubina al horno">
		<Category>Pescados y mariscos</Category>
		<Price>22,5</Price>
		<Description>pescado,lubina,horno</Description>
		<Visible>True</Visible>
		<Discount>0</Discount>
		<DiscountedUnit>0</DiscountedUnit>
	</Product>
	<Product name="Langostinos a la plancha">
		<Category>Pescados y mariscos</Category>
		<Price>21</Price>
		<Description>marisco,crustaceo,plancha</Description>
		<Visible>False</Visible>
		<Discount>0</Discount>
		<DiscountedUnit>0</DiscountedUnit>
	</Product>
	<Product name="Cigalas abiertas a la plancha">
		<Category>Pescados y mariscos</Category>
		<Price>22</Price>
		<Description>marisco,crustaceo,plancha</Description>
		<Visible>True</Visible>
		<Discount>0</Discount>
		<DiscountedUnit>0</DiscountedUnit>
	</Product>
</Products>
