=== srug86/restaurant-management-using-nfc.doc/listings/profile.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Profile (DNI, Name, Surname, Address)>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Surname (#PCDATA)>
<!ELEMENT Address (Street, Number, ZipCode, Town, State)>
<!ELEMENT Street (#PCDATA)>
<!ELEMENT Number (#PCDATA)>
<!ELEMENT ZipCode (#PCDATA)>
<!ELEMENT Town (#PCDATA)>
<!ELEMENT State (#PCDATA)>

=== srug86/restaurant-management-using-nfc.doc/listings/profile.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE profile SYSTEM "profile.dtd">
<Profile>
	<DNI>05692939W</DNI>
	<Name>Sergio</Name>
	<Surname>de la Rubia</Surname>
	<Address>
		<Street>C/Pedro Oviedo</Street>
		<Number>36</Number>
		<ZipCode>13270</ZipCode>
		<Town>Almagro</Town>
		<State>Ciudad Real</State>
	</Address>
</Profile>
