=== srug86/restaurant-management-using-nfc.doc/listings/restaurant.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Restaurant (Company, Address, Rate)>
<!ELEMENT Company (NIF, Name, Phone, Fax, Email)>
<!ELEMENT NIF (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Phone (#PCDATA)>
<!ELEMENT Fax (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Address (Street, Number, ZipCode, Town, State)>
<!ELEMENT Street (#PCDATA)>
<!ELEMENT Number (#PCDATA)>
<!ELEMENT ZipCode (#PCDATA)>
<!ELEMENT Town (#PCDATA)>
<!ELEMENT State (#PCDATA)>
<!ATTLIST Rate iva (#PCDATA)>
<!ATTLIST Rate discount (#PCDATA)>
<!ATTLIST Rate discountedVisit (#PCDATA)>

=== srug86/restaurant-management-using-nfc.doc/listings/restaurant.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE restaurant SYSTEM "restaurant.dtd">
<Restaurant>
	<Company>
		<NIF>70389210A</NIF>
		<Name>MobiCarta</Name>
		<Phone>926291111</Phone>
		<Fax>926294444</Fax>
		<Email>clients@mobicarta.es</Email>
	</Company>
	<Address>
		<Street>Paseo de la Universidad</Street>
		<Number>14</Number>
		<ZipCode>13071</ZipCode>
		<Town>Ciudad Real</Town>
		<State>Ciudad Real</State>
	</Address>
	<Rate iva="18" discount="5,0" discountedVisit="10"/>
</Restaurant>
